### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by epichickensoup** [tarsa129/j3d-animation-editor#2]
Please add a license, otherwise people aren't allowed to edit or fork your project. The MIT and GPL licenses are both really good open source licenses.

The MIT license is really simple and allows people to do a lot with your code, including edit it and include it in any other projects.

The GPL license gives you a bit more control; it allows edits and makes them also be under the GPL license. Not quite as permissive, but still much more permissive than no license.

Thank you!

**Comment by tarsa129** [comment]
Added an MIT license.
