### ISSUE TITLE
fix_array() missing 1 required positional argument: 'info'

### ISSUE THREAD

**Issue by Slycermusic** [tarsa129/j3d-animation-editor#3]
Hey,

When i try to export my bck with my bmd as .anim i'm getting this error
![image](https://user-images.githubusercontent.com/45978603/155612492-099eaf30-9e57-4a1c-9547-92e92930932f.png)

(loading back, then match with bmd and last export as .anim)

[bck.zip](https://github.com/tarsa129/j3d-animation-editor/files/8136572/bck.zip)
I uploaded both bck & bmd files

**Comment by tarsa129** [comment]
Sorry for not seeing this for months - I think that the current version resolves this issue.
